const express = require('express');

const mongoose = require("mongoose");

const Schema = mongoose.Schema();

const ApproveData = ({
    typeOfInstitute:{
        type:String,
        required:true
    },
    role:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    nameOfInstitute:{
        type:String,
        required:true
    },
    mailingAddress:{
        type:String,
        required:true
    },
    contactNumber:{
        type:String,
        required:true
    },
    emailId:{
        type:String,
        required:true
    },
    typeOfManagment:{
        type:String,
        required:true
    },
    functioningInOwnBuilding:{
        type:Boolean,
        required:true
    },
    purposeToFunctionInOwnBuiling:{
        type:Boolean,
        required:true
    },
    ownLand:{
        type:Boolean,
        required:true
    },
    noOfClassRooms:{
        type:String,
        required:true
    },
    examHallCapacity:{
        type:String,
        required:true
    },
    noOfLabs:{
        type:String,
        required:true
    },
    studentCanteenProvided:{
        type:Boolean,
        required:true
    },
    principalOffice:{
        type:Boolean,
        required:true
    },
    facultyRoom:{
        type:Boolean,
        required:true
    },
    officeRoom:{
        type:Boolean,
        required:true
    },
    reception:{
        type:Boolean,
        required:true
    },
    hockeyPlayground:{
        type:Boolean,
        required:true
    },
    cricketPlayground:{
        type:Boolean,
        required:true
    },
    footballPlayground:{
        type:Boolean,
        required:true
    },
    sharingPlayground:{
        type:Boolean,
        required:true
    },
    startDate:{
        type:String,
        required:true
    },
    inspectionDate:{
        type:String,
        required:true
    },
    nameOfOwners:{
        type:Array,
        required:true
    },
    cnicOfOwners:{
        type:Array,
        required:true
    },
    courses:{
        type:Array,
        required:true
    },
    approved:{
        type:Boolean
    }
})

module.exports = mongoose.model("Approve", ApproveData);